# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:http://bioigor.herokuapp.com"
ip-from-header: "_env:IP_FROM_HEADER:false"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

database:
  user:     "_env:PGUSER:maxlwztxrznump"
  password: "_env:PGPASS:v9oWiNDjRpymUOECXK33gOInxM"
  host:     "_env:PGHOST:ec2-23-21-73-32.compute-1.amazonaws.com"
  port:     "_env:PGPORT:5432"
  database: "_env:PGDATABASE:dakr8f8ul7ve7s"
  poolsize: "_env:PGPOOLSIZE:10"

copyright: Kindly developed by Igor Mandric for the Advanced Bioinformatics project
#analytics: UA-YOURCODE
